#!/usr/bin/env bash
set -euo pipefail

: "${PAYPAL_CLIENT_ID:?}"
: "${PAYPAL_SECRET:?}"

: "${PAYPAL_PLAN_MONTHLY_1499:=}"
: "${PAYPAL_PLAN_ANNUAL_4999:=}"
: "${PAYPAL_WEBHOOK_ID:=}"

: "${PAYPAL_ONESHOT_PRICE_EUR_IMAGE:=0.10}"
: "${PAYPAL_ONESHOT_PRICE_EUR_VIDEO:=0.30}"
: "${PAYPAL_ONESHOT_PRICE_EUR_LIFETIME:=100.00}"
: "${PAYPAL_ONESHOT_PACK10_IMAGES_EUR:=0.80}"
: "${PAYPAL_ONESHOT_PACK5_VIDEOS_EUR:=1.00}"

: "${CRISP_WEBSITE_ID:=}"

: "${JUICYADS_ZONE:=}"
: "${EXOCLICK_ZONE:=}"
: "${EROADVERTISING_ZONE:=}"
: "${POPADS_SITE_ID:=}"
: "${POPADS_ENABLE:=false}"

: "${JUICYADS_SNIPPET_B64:=}"
: "${EROADVERTISING_SNIPPET_B64:=}"

: "${IBG_ASSETS_BASE_URL:=}"

cat > ibg-env.js <<EOF
window.__IBG = {
  PAYPAL_CLIENT_ID: "${PAYPAL_CLIENT_ID}",
  PAYPAL_SECRET: "${PAYPAL_SECRET}",
  PAYPAL_PLAN_MONTHLY_ID: "${PAYPAL_PLAN_MONTHLY_1499}",
  PAYPAL_PLAN_ANNUAL_ID: "${PAYPAL_PLAN_ANNUAL_4999}",
  PAYPAL_WEBHOOK_ID: "${PAYPAL_WEBHOOK_ID}",
  PRICES: {
    IMAGE_EUR: "${PAYPAL_ONESHOT_PRICE_EUR_IMAGE}",
    VIDEO_EUR: "${PAYPAL_ONESHOT_PRICE_EUR_VIDEO}",
    LIFETIME_EUR: "${PAYPAL_ONESHOT_PRICE_EUR_LIFETIME}",
    PACK10_IMAGES_EUR: "${PAYPAL_ONESHOT_PACK10_IMAGES_EUR}",
    PACK5_VIDEOS_EUR: "${PAYPAL_ONESHOT_PACK5_VIDEOS_EUR}"
  },
  CRISP_WEBSITE_ID: "${CRISP_WEBSITE_ID}",
  ADS: {
    JUICYADS_ZONE: "${JUICYADS_ZONE}",
    EXOCLICK_ZONE: "${EXOCLICK_ZONE}",
    EROADVERTISING_ZONE: "${EROADVERTISING_ZONE}",
    POPADS_SITE_ID: "${POPADS_SITE_ID}",
    POPADS_ENABLE: "${POPADS_ENABLE}",
    JUICYADS_SNIPPET_B64: "${JUICYADS_SNIPPET_B64}",
    EROADVERTISING_SNIPPET_B64: "${EROADVERTISING_SNIPPET_B64}"
  },
  ASSETS: {
    BASE_URL: "${IBG_ASSETS_BASE_URL}"
  }
};
EOF

echo "OK: ibg-env.js escrito"
